export * from './client'
export * from './errors'
export { authService } from './services/auth.service'
export { programsService } from './services/programs.service'
export { studentsService } from './services/students.service'
export { teachersService } from './services/teachers.service'
export { guardiansService } from './services/guardians.service'
export { registrationsService } from './services/registrations.service'
export { subjectsService } from './services/subjects.service'
export { timetableService } from './services/timetable.service'
